### ISSUE TITLE
Segfault on Manjaro Linux

### ISSUE THREAD

**Issue by XavilPergis** [surrsurus/edgequest#15]
There seems to be a problem with libtcod.

Why.

Pls fix m9.

**Comment by TriangularEgg** [comment]
No clue

**Comment by TriangularEgg** [comment]
Does [this](https://stackoverflow.com/questions/31375177/why-might-mallocd-memory-from-a-shared-library-be-inaccessible-to-the-applicati) help you? Why don't you try running script how he suggests? He states that it works on Ubuntu (which is very true of this game) but not on other distributions unless ran as root.

**Comment by XavilPergis** [comment]
Sudo does not help, nor does running it as root.
I also tried setting all permissions to rwx on libtcod.py and libtcod.pyc, but that did not help either.

**Comment by XavilPergis** [comment]
Note: python3.5 does not seem to be segfaulting, but instead throwing a TypeError around line 711 in edgequest.py

**Comment by TriangularEgg** [comment]
That's because the library was intended to be used with Python 2. There is no backwards compatibility with Python 3 at the moment. I'll continue looking into solutions.

**Comment by XavilPergis** [comment]
It seems that c_char_p in python3.5 now takes bytes instead of a string.
Simply changing c_char_p(<str>) to c_char_p(str.encode(<str>)) does not throw a TypeError

**Comment by TriangularEgg** [comment]
That's interesting. If you make the necessary changes to libtcodpy and if it runs can you attach the file so I can implement it?

**Comment by XavilPergis** [comment]
A little progress update: I have gotten the window not to crash immediately, but it displays mangled text, so I cannot figure out how to navigate the GUIs

**Comment by XavilPergis** [comment]
Oops, that was my fault; I removed some formatting arguments from tcod init

**Comment by TriangularEgg** [comment]
Post screenshots of any problems if you can.

**Comment by XavilPergis** [comment]
I have gotten it to run, but I had to convert x/y coords to ints, which is likely what causes this:
![screenshot5](https://cloud.githubusercontent.com/assets/4951693/12691834/e89fca96-c6bd-11e5-91f2-b69d207bdaf0.png)

**Comment by TriangularEgg** [comment]
Interesting. X/y coords should already be integers. Are you talking about things like (player.x, player.y)? Those are tuples and don't need to be casted to integers. I may be making the wrong assumption, but can you show what values are changed?

**Comment by XavilPergis** [comment]
One instance of it seems to be right here, while printing "Edgequest": (line 1951)
`libtcod.console_print_ex(0, SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2 - 4, libtcod.BKGND_NONE, libtcod.CENTER, 'Edgequest')`

**Comment by TriangularEgg** [comment]
Okay that makes sense. Python 2 has integer division so no extra casting is needed. Make sure to use math.floor() then in Python 3.

**Comment by XavilPergis** [comment]
that did not seem to fix the problem.

**Comment by surrsurus** [comment]
You finally installed Ubuntu I hear
