### ISSUE TITLE
Edgequest compatibility problems on Windows 10

### ISSUE THREAD

**Issue by Nuke-Is-T-sided** [surrsurus/edgequest#16]
https://gyazo.com/102850950427740e6bb6f433408f2ac0
idk what to do. I installed Python 2.7

**Comment by TriangularEgg** [comment]
Follow the readme instructions?

**Comment by TriangularEgg** [comment]
Also send a screenshot or copypaste of the problem

**Comment by Nuke-Is-T-sided** [comment]
I followed the readme instructions and the link i added is a gif of me trying to open it. No error message pops up, it just doesn't open the game.

**Comment by TriangularEgg** [comment]
open the edgequest file with the python idle then press f5 to run it and send the error message to me.

**Comment by Nuke-Is-T-sided** [comment]
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
============== RESTART: C:\Games\edgequest-master\edgequest.py ==============

Traceback (most recent call last):
  File "C:\Games\edgequest-master\edgequest.py", line 9, in <module>
    from colors import *
  File "C:\Games\edgequest-master\colors.py", line 1, in <module>
    from modules import libtcodpy as libtcod
  File "C:\Games\edgequest-master\modules\libtcodpy.py", line 60, in <module>
    _lib = ctypes.cdll['./libtcod-VS.dll']
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in __getitem__
    return getattr(self, name)
  File "C:\Python27\lib\ctypes\__init__.py", line 435, in __getattr__
    dll = self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
>>>

**Comment by surrsurus** [comment]
Try the latest version again

**Comment by surrsurus** [comment]
For all future reference, this issue is solved by installing 32 bit python.
