### ISSUE TITLE
Up stairs still not spawning after going up one floor

### ISSUE THREAD

**Issue by FreshmanPresident** [surrsurus/edgequest#17]
I have used the latest version and i rekt gaben lord of steam but no stairs will spawn

**Comment by surrsurus** [comment]
I'll need screenshots to verify. Stairs spawn under items, so make sure you check them with your cursor. Also there will be a planned feature to auto travel to the nearest up/down stairs

**Comment by surrsurus** [comment]
Sorry about this. I originally thought this was a joke and completely ignored it because after all I'm such an amazing programmer and I don't make mistakes. Turns out it was actually not working since... like forever ago. Thanks for letting me know. As of the latest master this issue is resolved.
