### ISSUE TITLE
Add feature so when game breaks in full screen you can get out

### ISSUE THREAD

**Issue by FreshmanPresident** [surrsurus/edgequest#21]

**Comment by surrsurus** [comment]
This is a good idea. Has the game been breaking though? Make sure to download the latest master.

**Comment by surrsurus** [comment]
To be honest, I think it would be better to have a feature where the game doesn't break at all

**Comment by XavilPergis** [comment]
That would be a *very* hard feature to implement :)

**Comment by surrsurus** [comment]
Yep. I think instead of focusing on something to break the while loops, it's best to find where the problems are at so that they don't break to begin with. As far as I know, I haven't occurred errors like this before, but I don't doubt there are bugs.

**Comment by surrsurus** [comment]
I'm closing this issue. If you can pinpoint the times when your game freezes, we can work on that if you create another issue.
