### ISSUE TITLE
Grab the dependencies for a smaller footprint

### ISSUE THREAD

**Issue by XavilPergis** [surrsurus/edgequest#23]
Maybe have a shell file that gets and unpacks simplejson and other large files?

If that is not a viable option, doing everything in a Python script might work...

**Comment by surrsurus** [comment]
The entirety of `edgequest-master.zip` is under a megabyte. Unzipped is around 1.8 megabytes. This is a good idea but maybe in the future, though I may have misunderstood what you're saying.

**Comment by FreshmanPresident** [comment]
It's fucking bloatware you need to replace it

**Comment by surrsurus** [comment]
Let's come back to this later.
