### ISSUE TITLE
Theme based off black and red?

### ISSUE THREAD

**Issue by FreshmanPresident** [surrsurus/edgequest#29]
"volcanic": {
        "highlight": {
            "wall": "#ff0000",
            "ground": "#ff0000"
        },
        "ground": {
            "light": "#cc1111",
            "dark": "#000022"
        },
        "wall": {
            "light": "#333333",
            "dark": "#000000"
        },
        "accent": {
            "light": "#ffffff"
        }
    },

**Comment by XavilPergis** [comment]
lol fuck you ur them is trash xdddddd

**Comment by XavilPergis** [comment]
```json
"volcanic": {
"highlight": {
"wall": "#ff0000",
"ground": "#ff0000"
},
"ground": {
"light": "#cc1111",
"dark": "#22"
},
"wall": {
"light": "#333333",
"dark": "#000000"
},
"accent": {
"light": "#ffffff"
}
},
```

**Comment by XavilPergis** [comment]
```json
"volcanic": {
"highlight": {
"wall": "#ff0000",
"ground": "#ff0000"
},
"ground": {
"light": "#cc1111",
"dark": "#000022"
},
"wall": {
"light": "#333333",
"dark": "#000000"
},
"accent": {
"light": "#ffffff"
}
},
```

**Comment by surrsurus** [comment]
A theme based off black and red sounds interesting. I'll start messing around with these themes and adding the one I like best.

**Comment by surrsurus** [comment]
Also, thank you for contributing.

**Comment by surrsurus** [comment]
In testing Mike's theme, the theme instantly broke which revealed a bug that showed that Max's logger cannot actually print out a stack trace, so Mike thank you for your two-birds one stone work ethic.

**Comment by surrsurus** [comment]
After reviewing both themes, I thought both were equally okay, so I just made my own theme called 'magma' that is a red and black theme.

**Comment by surrsurus** [comment]
You can now access the 'magma' theme in the latest master.
