### ISSUE TITLE
A* bug

### ISSUE THREAD

**Issue by XavilPergis** [surrsurus/edgequest#31]
### What Happened
A* pathfinding gets stuck in an infinite loop where it cannot push the tamed mob out of the way
### What Should have Happened
Movement of the player *should* displace the tamed mob
### Steps to reproducing

  1. Go into corridor
  2. Have tamed mob following
  3. Mouse click on other side of tamed mob

**Comment by surrsurus** [comment]
Thanks. I'll look into this right away.

**Comment by surrsurus** [comment]
I've confirmed this bug indeed does exist. I'll have the fix shortly

**Comment by XavilPergis** [comment]
Yeah, if you could test to see if a path is blocked, I would love that.
It would prevent freezes when testing new world generators.

**Comment by surrsurus** [comment]
Okay, so the problem was in the mouse_move_astar. It would run continuously even if the A* path wasn't blocked, so that's been fixed. Thanks for letting me know about the bug.
