### ISSUE TITLE
Keep up the good work. proud of you.

### ISSUE THREAD

**Issue by FreshmanPresident** [surrsurus/edgequest#33]
Wow this is a great game! It's way better than my implementation of libtcod in a game of snake that has no real rendering system and stores everything to a list that's updated every frame!

**Comment by surrsurus** [comment]
I'm glad you enjoy the game.

**Comment by FreshmanPresident** [comment]
Snake is also so bad because it's rendering system is so slow compared to edgequest's rendering system where It redraws the entire screen every frame.

**Comment by XavilPergis** [comment]
It would probably take *more* CPU figuring out every single character's delta and drawing to two locations for every object. Not to mention for fragile too!
