### ISSUE TITLE
FOV enable / disable messages confused

### ISSUE THREAD

**Issue by sudo-prime** [surrsurus/edgequest#65]
When you disable FOV, the following message is printed: "Your third eye closes, concealing the universe in fog.". This message should instead print when FOV is enabled. The same occurs when enabling FOV - instead of printing the above message, it prints the message associated with opening your third eye.

**Comment by surrsurus** [comment]
Thanks for reporting. Yeah the relevant code is in `Engine`, as the engine directly takes control over a lot of the game elements in wizard mode (rightfully so), should be simple fix, but still important to recognize these issues when they come up.

**Comment by surrsurus** [comment]
9fadfd7 fixes this issue.
